// Copyright 2026 Infinite Gameworks. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Paper2DPlusTypes.h"
#include "PaperFlipbook.h"
#include "Engine/Texture2D.h"
#include "GameplayTagContainer.h"
#include "Paper2DPlusCharacterDataAsset.generated.h"

/**
 * Animation data with hitbox information and sprite extraction metadata
 */
USTRUCT(BlueprintType)
struct PAPER2DPLUS_API FAnimationHitboxData
{
	GENERATED_BODY()

	// ==========================================
	// EXISTING FIELDS (for backward compatibility)
	// ==========================================

	/** Name of the animation/flipbook group */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation")
	FString AnimationName;

	/** Optional reference to the Paper2D Flipbook for this animation */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation")
	TSoftObjectPtr<UPaperFlipbook> Flipbook;

	/** All frames in this animation with hitbox data */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation")
	TArray<FFrameHitboxData> Frames;

	/** Source texture this animation was extracted from */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sprite Source")
	TSoftObjectPtr<UTexture2D> SourceTexture;

	/** Per-frame extraction metadata */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sprite Source")
	TArray<FSpriteExtractionInfo> FrameExtractionInfo;

	/** Output path where sprites for this animation are saved */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sprite Source")
	FString SpritesOutputPath;

	// ==========================================
	// EXISTING HELPER FUNCTIONS
	// ==========================================

	/** Get frame data by index */
	const FFrameHitboxData* GetFrame(int32 Index) const
	{
		if (Frames.IsValidIndex(Index))
		{
			return &Frames[Index];
		}
		return nullptr;
	}

	/** Get frame data by name */
	const FFrameHitboxData* GetFrameByName(const FString& FrameName) const
	{
		for (const FFrameHitboxData& Frame : Frames)
		{
			if (Frame.FrameName.Equals(FrameName, ESearchCase::IgnoreCase))
			{
				return &Frame;
			}
		}
		return nullptr;
	}

	/** Get total frame count */
	int32 GetFrameCount() const
	{
		return Frames.Num();
	}

	/** Check if this animation has extraction info available */
	bool HasExtractionInfo() const
	{
		return !SourceTexture.IsNull() && FrameExtractionInfo.Num() > 0;
	}
};

/**
 * Binding from an animation group to one or more animation entries + metadata.
 * Groups reference existing animations by name (no data duplication).
 * Array order is significant for combo systems (index 0 = first, etc.).
 */
USTRUCT(BlueprintType)
struct PAPER2DPLUS_API FAnimationGroupBinding
{
	GENERATED_BODY()

	/** Animation names referencing Animations[].AnimationName entries. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation Groups")
	TArray<FString> AnimationNames;

	/** PaperZD AnimSequence for this group (soft ref — no hard dependency on PaperZD). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation Groups")
	TSoftObjectPtr<UObject> PaperZDSequence;

	/** Arbitrary metadata assets keyed by name (e.g., "SoundCue", "Montage"). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation Groups")
	TMap<FName, TSoftObjectPtr<UObject>> Metadata;
};

/** Serializable key-value pair for group bindings in JSON export. */
USTRUCT()
struct PAPER2DPLUS_API FSerializableGroupBinding
{
	GENERATED_BODY()

	UPROPERTY()
	FString Tag;

	UPROPERTY()
	FAnimationGroupBinding Binding;
};

UENUM(BlueprintType)
enum class ECharacterDataValidationSeverity : uint8
{
	Info	UMETA(DisplayName = "Info"),
	Warning UMETA(DisplayName = "Warning"),
	Error	UMETA(DisplayName = "Error")
};


/** Internal serializable payload for JSON import/export. */
USTRUCT()
struct PAPER2DPLUS_API FCharacterDataAssetSerializablePayload
{
	GENERATED_BODY()

	UPROPERTY()
	int32 SchemaVersion = 1;

	UPROPERTY()
	FString DisplayName;

	UPROPERTY()
	TArray<FAnimationHitboxData> Animations;

	UPROPERTY()
	int32 DefaultAlphaThreshold = 10;

	UPROPERTY()
	int32 DefaultPadding = 0;

	UPROPERTY()
	int32 DefaultMinSpriteSize = 4;

	/** Group bindings serialized as array of key-value pairs (avoids TMap<FGameplayTag> JSON issues). */
	UPROPERTY()
	TArray<FSerializableGroupBinding> GroupBindings;
};

/** Validation issue generated by CharacterData asset validation. */
USTRUCT(BlueprintType)
struct PAPER2DPLUS_API FCharacterDataValidationIssue
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Validation")
	ECharacterDataValidationSeverity Severity = ECharacterDataValidationSeverity::Info;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Validation")
	FString Context;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Validation")
	FString Message;
};

/**
 * Character Data Asset containing all animation hitbox data.
 * Manages flipbooks, hitboxes, sockets, and extraction metadata across all character animations.
 */
UCLASS(BlueprintType, NotBlueprintable)
class PAPER2DPLUS_API UPaper2DPlusCharacterDataAsset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPaper2DPlusCharacterDataAsset();

	// ==========================================
	// EXISTING PROPERTIES (for backward compatibility)
	// ==========================================

	/** Display name for this character data (e.g., character name) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Character Data")
	FString DisplayName;

	/** All animations with their hitbox data */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Character Data")
	TArray<FAnimationHitboxData> Animations;

	// ==========================================
	// ANIMATION GROUP BINDINGS
	// ==========================================

	/** Group-to-animation mappings. Each GameplayTag group maps to one or more animation entries + metadata. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Animation Groups",
		meta = (Categories = "Paper2DPlus.Animation"))
	TMap<FGameplayTag, FAnimationGroupBinding> GroupBindings;

	/** Alpha threshold to use for sprite extraction */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Extraction Settings")
	int32 DefaultAlphaThreshold = 10;

	/** Padding to apply around detected sprites */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Extraction Settings")
	int32 DefaultPadding = 0;

	/** Minimum sprite size filter */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Extraction Settings")
	int32 DefaultMinSpriteSize = 4;

	// ==========================================
	// EXISTING LOOKUP FUNCTIONS
	// ==========================================

	/** Get all animation names */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	TArray<FString> GetAnimationNames() const;

	/** Get animation data by name */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool GetAnimation(const FString& AnimationName, FAnimationHitboxData& OutAnimation) const;

	/** Get animation data by index */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool GetAnimationByIndex(int32 Index, FAnimationHitboxData& OutAnimation) const;

	/** Get frame count for an animation */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	int32 GetFrameCount(const FString& AnimationName) const;

	/** Get frame data by animation name and frame index */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool GetFrame(const FString& AnimationName, int32 FrameIndex, FFrameHitboxData& OutFrame) const;

	/** Get frame data by animation name and frame name */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool GetFrameByName(const FString& AnimationName, const FString& FrameName, FFrameHitboxData& OutFrame) const;

	/** Find animation index by Flipbook reference */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool FindAnimationByFlipbook(UPaperFlipbook* Flipbook, FAnimationHitboxData& OutAnimation) const;

	/** Fast lookup helper that avoids copying animation data. */
	const FAnimationHitboxData* FindAnimationByFlipbookPtr(UPaperFlipbook* Flipbook) const;

	/** Get a const pointer to animation data by name (no copy). */
	const FAnimationHitboxData* FindAnimationPtr(const FString& AnimationName) const;

	// ==========================================
	// DIRECT HITBOX ACCESS
	// ==========================================

	/** Get all hitboxes for a specific frame */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	TArray<FHitboxData> GetHitboxes(const FString& AnimationName, int32 FrameIndex) const;

	/** Get hitboxes of a specific type for a frame */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	TArray<FHitboxData> GetHitboxesByType(const FString& AnimationName, int32 FrameIndex, EHitboxType Type) const;

	/** Get all sockets for a specific frame */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	TArray<FSocketData> GetSockets(const FString& AnimationName, int32 FrameIndex) const;

	/** Find a specific socket by name */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	bool FindSocket(const FString& AnimationName, int32 FrameIndex, const FString& SocketName, FSocketData& OutSocket) const;

	// ==========================================
	// ASSET INFO
	// ==========================================

	/** Get total number of animations */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	int32 GetAnimationCount() const { return Animations.Num(); }

	/** Check if a specific animation exists */
	UFUNCTION(BlueprintPure, Category = "Character Data")
	bool HasAnimation(const FString& AnimationName) const;

	// ==========================================
	// ANIMATION GROUP LOOKUPS
	// ==========================================

	/** Get all animation data for a group, in array order (for combo progression). */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	TArray<FAnimationHitboxData> GetAnimationsForGroup(FGameplayTag Group) const;

	/** Get all loaded flipbooks for a group. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	TArray<UPaperFlipbook*> GetFlipbooksForGroup(FGameplayTag Group) const;

	/** Get the first flipbook for a group, or nullptr if unmapped. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	UPaperFlipbook* GetFirstFlipbookForGroup(FGameplayTag Group) const;

	/** Get a random flipbook for a group (non-deterministic — not safe for networked use). */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	UPaperFlipbook* GetRandomFlipbookForGroup(FGameplayTag Group) const;

	/** Get the PaperZD AnimSequence for a group. Calls LoadSynchronous — cache result in hot paths. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	UObject* GetPaperZDSequenceForGroup(FGameplayTag Group) const;

	/** Get a metadata asset for a group by key. Calls LoadSynchronous — cache result in hot paths. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	UObject* GetGroupMetadata(FGameplayTag Group, FName Key) const;

	/** Get all metadata keys for a group. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	TArray<FName> GetGroupMetadataKeys(FGameplayTag Group) const;

	/** Check if a group has a metadata entry for the given key. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	bool HasGroupMetadata(FGameplayTag Group, FName Key) const;

	/** Get the full group binding struct (animations + metadata) for a group. Returns false if unmapped. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	bool GetGroupBinding(FGameplayTag Group, FAnimationGroupBinding& OutBinding) const;

	/** Check if this asset has a mapping for the given group. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	bool HasGroup(FGameplayTag Group) const;

	/** Get all roles that have been mapped in this asset. */
	UFUNCTION(BlueprintPure, Category = "Animation Groups")
	TArray<FGameplayTag> GetAllMappedGroups() const;

	/** Get the number of animations mapped to a group (useful for combo systems). */
	UFUNCTION(BlueprintPure, Category = "Animation Groups", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	int32 GetAnimationCountForGroup(FGameplayTag Group) const;

	// ==========================================
	// ATTACK BOUNDS (AI HELPERS)
	// ==========================================

	/** Get the max attack range across ALL animations (distance from origin to furthest attack hitbox edge). */
	UFUNCTION(BlueprintPure, Category = "Attack Bounds")
	float GetMaxAttackRange() const;

	/** Get the max attack range for a specific animation group. */
	UFUNCTION(BlueprintPure, Category = "Attack Bounds", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	float GetAttackRangeForGroup(FGameplayTag Group) const;

	/** Get the max attack range for a specific animation by name. */
	UFUNCTION(BlueprintPure, Category = "Attack Bounds")
	float GetAttackRangeForAnimation(const FString& AnimationName) const;

	/** Get the combined bounds (FBox2D) of all attack hitboxes across all frames of a group. */
	UFUNCTION(BlueprintPure, Category = "Attack Bounds", meta = (GameplayTagFilter = "Paper2DPlus.Animation"))
	FBox2D GetAttackBoundsForGroup(FGameplayTag Group) const;

	/** Get the combined bounds (FBox2D) of all attack hitboxes across all frames of an animation. */
	UFUNCTION(BlueprintPure, Category = "Attack Bounds")
	FBox2D GetAttackBoundsForAnimation(const FString& AnimationName) const;

	/** Validate the character data asset for common data issues.
	 *  @return true when no errors are found (warnings allowed). */
	UFUNCTION(BlueprintCallable, Category = "Validation")
	bool ValidateCharacterDataAsset(TArray<FCharacterDataValidationIssue>& OutIssues) const;

	/** Trim trailing frame/extraction metadata beyond the flipbook keyframe count for one animation.
	 *  @return Total entries removed from all arrays for this animation. */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	int32 TrimTrailingFrameData(int32 AnimationIndex);

	/** Trim trailing frame/extraction metadata for all animations.
	 *  @return Total entries removed across all animations. */
	UFUNCTION(BlueprintCallable, Category = "Character Data")
	int32 TrimAllTrailingFrameData();

	/** Copy all hitboxes/sockets from SourceFrameIndex to an inclusive frame range in an animation.
	 *  @return true if operation succeeds. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Batch")
	bool CopyFrameDataToRange(const FString& AnimationName, int32 SourceFrameIndex, int32 RangeStart, int32 RangeEnd, bool bIncludeSockets = true);

	/** Mirror hitboxes horizontally in an inclusive frame range using PivotX.
	 *  @return number of hitboxes mirrored. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Batch")
	int32 MirrorHitboxesInRange(const FString& AnimationName, int32 RangeStart, int32 RangeEnd, int32 PivotX);

	/** Set sprite flip state in an inclusive frame range.
	 *  @return number of frames updated. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Batch")
	int32 SetSpriteFlipInRange(const FString& AnimationName, int32 RangeStart, int32 RangeEnd, bool bInFlipX, bool bInFlipY);

	/** Set sprite flip state across every frame of an animation.
	 *  @return number of frames updated. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Batch")
	int32 SetSpriteFlipForAnimation(const FString& AnimationName, bool bInFlipX, bool bInFlipY);

	/** Set sprite flip state across all animations in the asset.
	 *  @return number of frames updated. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Batch")
	int32 SetSpriteFlipForAllAnimations(bool bInFlipX, bool bInFlipY);

	/** Legacy CharacterData JSON schema version used before explicit schema stamping. */
	static constexpr int32 CharacterDataJsonLegacySchemaVersion = 0;

	/** Current CharacterData JSON schema version. */
	static constexpr int32 CharacterDataJsonSchemaVersion = 3;

	/** Get current CharacterData JSON schema version. */
	UFUNCTION(BlueprintPure, Category = "Character Data|Serialization")
	int32 GetCharacterDataJsonSchemaVersion() const { return CharacterDataJsonSchemaVersion; }

	/** Export CharacterData content to a deterministic JSON string. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Serialization")
	bool ExportToJsonString(FString& OutJson) const;

	/** Import CharacterData content from JSON string. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Serialization")
	bool ImportFromJsonString(const FString& JsonString);

	/** Export CharacterData to a JSON file. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Serialization")
	bool ExportToJsonFile(const FString& FilePath) const;

	/** Import CharacterData from a JSON file. */
	UFUNCTION(BlueprintCallable, Category = "Character Data|Serialization")
	bool ImportFromJsonFile(const FString& FilePath);

	/** Get asset primary ID for async loading */
	virtual FPrimaryAssetId GetPrimaryAssetId() const override;

	/** Sync hitbox Frames[] array to match the flipbook frame count for an animation.
	 *  Preserves existing data, appends empty FFrameHitboxData for new frames. */
	void SyncFramesToFlipbook(int32 AnimationIndex);

	/** Sync all animations' frame arrays to their flipbooks */
	void SyncAllFramesToFlipbooks();

	/** Update animation name references in GroupBindings when an animation is renamed. */
	void UpdateGroupBindingAnimationName(const FString& OldName, const FString& NewName);

	/** Remove an animation name from all GroupBindings entries. */
	void RemoveAnimationFromGroupBindings(const FString& AnimationName);

	/** Post-load hook for asset migration */
	virtual void PostLoad() override;

#if WITH_EDITOR
	virtual void PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

protected:
	/** Internal lookup - find animation by name */
	const FAnimationHitboxData* FindAnimation(const FString& AnimationName) const;

private:
	/** Migrate imported JSON payload to the current schema version when possible. */
	static bool MigrateSerializablePayloadToCurrentSchema(FCharacterDataAssetSerializablePayload& InOutPayload);

	void RebuildFlipbookLookupCache() const;
	void RebuildNameLookupCache() const;

	/** Cached map to accelerate flipbook -> animation lookup in hot paths. */
	mutable TMap<TObjectPtr<UPaperFlipbook>, int32> FlipbookToAnimationIndexCache;

	/** Whether FlipbookToAnimationIndexCache is synchronized with Animations. */
	mutable bool bFlipbookLookupCacheValid = false;

	/** Number of Animations entries when the flipbook cache was last built. */
	mutable int32 CachedAnimationCount = 0;

	/** Cached map to accelerate name -> animation lookup. */
	mutable TMap<FString, int32> NameToAnimationIndexCache;

	/** Whether NameToAnimationIndexCache is synchronized with Animations. */
	mutable bool bNameLookupCacheValid = false;

	void RebuildGroupLookupCache() const;

	/** Cached map: group tag -> resolved animation indices (into Animations array). */
	mutable TMap<FGameplayTag, TArray<int32>> GroupToAnimationIndicesCache;

	/** Whether GroupToAnimationIndicesCache is synchronized with GroupBindings/Animations. */
	mutable bool bGroupLookupCacheValid = false;
};
